### ISSUE TITLE
Mint function calls `callRecipient` while burn doesn't

### ISSUE THREAD

**Issue by rstormsf** [jacquesd/eip777#34] opened 2018-02-21 03:34 UTC
https://github.com/jacquesd/eip777/blob/master/contracts/ReferenceToken.sol#L140

```js
    function mint(address _tokenHolder, uint256 _amount, bytes _operatorData) public onlyOwner {
        requireMultiple(_amount);
        mTotalSupply = mTotalSupply.add(_amount);
        mBalances[_tokenHolder] = mBalances[_tokenHolder].add(_amount);

        callRecipient(msg.sender, 0x0, _tokenHolder, _amount, "", _operatorData, true);

        Minted(msg.sender, _tokenHolder, _amount, _operatorData);
        if (mErc20compatible) { Transfer(0x0, _tokenHolder, _amount); }
    }
```

burn:

```js
    function burn(address _tokenHolder, uint256 _amount, bytes _userData, bytes _operatorData) public onlyOwner {
        requireMultiple(_amount);
        require(balanceOf(_tokenHolder) >= _amount);

        mBalances[_tokenHolder] = mBalances[_tokenHolder].sub(_amount);
        mTotalSupply = mTotalSupply.sub(_amount);

        Burned(msg.sender, _tokenHolder, _amount, _userData, _operatorData);
        if (mErc20compatible) { Transfer(_tokenHolder, 0x0, _amount); }
    }
```

1. If you still need it, why burn method doesn't call `callRecipient` if _operatorData is provided? 

I believe mint/burn function has to provide 2 methods with different params(overloaded function):
Traditional way without `bytes _data`
and new way with `bytes _data` (overloaded function)

**Comment by jacquesd** [comment] 2018-02-23 03:02
`callRecipient` is just a helper to call `tokensReceived` on the address which received the tokens.

When minting the recipient is `_tokenHolder`, but when burning there is no recipient which is why `tokensReceived` is not called.

I checked and the standard does indeed mention the following in the specification for `tokensReceived`:
> > - `to`: tokens recipient (or `0x` for burning)
> > - `amount`: number of tokens transferred, minted or burned

This is a mistake and which will be fixed. In addition I can understand the confusion and I will add a clarification regarding not calling `tokensToSend` when burning.

Operator data is provided to potentially indicate the reason why the tokens were burned. The operator data is used in the `Burned` event.

Regarding the mint/burn functions, those are *not* part of the standard and just provided as examples for devs to understand the expected behavior when minting/burning.

There are many different ways one could  mint/burn tokens. This depends on the specific tokens. What is important is which events to fire and which function to call or not depending on the situation.

**Closed** 2018-02-24 09:27 UTC
